version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
  - copyloopvar
  - dupl
  - dupword
  - errcheck
  - ginkgolinter
  - goconst
  - gocyclo
  - govet
  - ineffassign
  - lll
  - misspell
  - nakedret
  - prealloc
  - staticcheck
  - unconvert
  - unparam
  - unused
  exclusions:
    generated: lax
    rules:
    - linters:
      - goconst
      - ineffassign
      - lll
      - prealloc
      - staticcheck
      - unparam
      - unused
      path: test/*
    - linters:
      - lll
      path: api/*
    - linters:
      - dupl
      - lll
      path: internal/*
    - linters:
      - lll
      path: pkg/*
    paths:
    - third_party$
    - builtin$
    - examples$
formatters:
  enable:
  - gci
  - gofmt
  - goimports
  settings:
    gci:
      sections:
      - standard
      - default
      - prefix(github.com/project-codeflare/appwrapper)
      - blank
      - dot
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
