repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
  - id: go-fmt
  - id: go-mod-tidy
- repo: local
  hooks:
  - id: golangci-lint
    name: golangci-lint
    entry: make lint-fix
    language: system
    pass_filenames: false
  - id: generate-apiref
    name: generate-apiref
    entry: make generate-apiref
    language: system
    pass_filenames: false
- repo: https://github.com/google/yamlfmt
  rev: v0.10.0
  hooks:
  - id: yamlfmt
    exclude: ^config/crd/bases/.*\.yaml|config/rbac/role\.yaml|config/webhook/manifests\.yaml
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
    exclude: site/_pages/appwrapper.v1beta2.md
  - id: end-of-file-fixer
    exclude: hack/boilerplate.go.txt|site/_pages/appwrapper.v1beta2.md
  - id: mixed-line-ending
    args: ["--fix=lf"]
