# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# 1 control plane node and 1 worker node
nodes:
# the control plane node config
- role: control-plane
  # kubernetes version 1.27.10 from kind v0.22.0
  image: kindest/node:v1.27.10@sha256:e6b2f72f22a4de7b957cd5541e519a8bef3bae7261dd30c6df34cd9bdd3f8476
# the worker
- role: worker
  # kubernetes version 1.27.10 from kind v0.22.0
  image: kindest/node:v1.27.10@sha256:e6b2f72f22a4de7b957cd5541e519a8bef3bae7261dd30c6df34cd9bdd3f8476
