# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# 1 control plane node and 1 worker node
nodes:
# the control plane node config
- role: control-plane
  # kubernetes version 1.27.1 from kind v0.19.0
  image: kindest/node:v1.27.1@sha256:b7d12ed662b873bd8510879c1846e87c7e676a79fefc93e17b2a52989d3ff42b
# the worker
- role: worker
  # kubernetes version 1.27.1 from kind v0.19.0
  image: kindest/node:v1.27.1@sha256:b7d12ed662b873bd8510879c1846e87c7e676a79fefc93e17b2a52989d3ff42b
