apiVersion: workload.codeflare.dev/v1beta2
kind: AppWrapper
metadata:
  name: sample-job
  labels:
    kueue.x-k8s.io/queue-name: default-queue
  annotations:
    workload.codeflare.dev.appwrapper/successTTLDuration: "1m"
spec:
  components:
  - template:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: sample-job
      spec:
        template:
          spec:
            restartPolicy: Never
            containers:
            - name: busybox
              image: quay.io/project-codeflare/busybox:1.36
              command: ["sh", "-c", "sleep 600"]
              resources:
                requests:
                  cpu: 1
