apiVersion: workload.codeflare.dev/v1beta2
kind: AppWrapper
metadata:
  name: sample-failing-pod
  labels:
    kueue.x-k8s.io/queue-name: user-queue
  annotations:
    workload.codeflare.dev.appwrapper/failureGracePeriodDuration: 10s
    workload.codeflare.dev.appwrapper/resetPauseDuration: 10s
    workload.codeflare.dev.appwrapper/retryLimit: "1"
    workload.codeflare.dev.appwrapper/debuggingFailureDeletionDelayDuration: "5m"
spec:
  components:
  - template:
      apiVersion: v1
      kind: Pod
      metadata:
        name: sample-failing-pod
      spec:
        restartPolicy: Never
        initContainers:
        - name: stall
          image: quay.io/project-codeflare/busybox:1.36
          command: ["sh", "-c", "sleep 10"]
        containers:
        - name: busybox
          image: quay.io/project-codeflare/busybox:1.36
          command: ["sh", "-c", "sleep 5; exit 1"]
          resources:
            requests:
              cpu: 1
