kind: ConfigMap
apiVersion: v1
metadata:
  name: operator-config
data:
  config.yaml: |
    appwrapper:
      standaloneMode: true
      manageJobsWithoutQueueName: false
    controllerManager:
      health:
        bindAddress: ":8081"
      metrics:
        bindAddress: "127.0.0.1:8080"
      leaderElection: true
