kind: ConfigMap
apiVersion: v1
metadata:
  name: operator-config
data:
  config.yaml: |
    appwrapper:
      enableKueueIntegrations: false
    controllerManager:
      health:
        bindAddress: "localhost:0"
      metrics:
        bindAddress: "localhost:0"
      leaderElection: false
    webhooksEnabled: false
