# Actions to take when a release is tagged

name: release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'project-codeflare/appwrapper'
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: validate tag format
      run: |
        if [[ ${GITHUB_REF_NAME} =~ ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$ ]]; then
          echo "Tag format is valid."
        else
          echo "Invalid tag format: ${GITHUB_REF_NAME}"
          exit 1
        fi
        echo "APPWRAPPER_VERSION=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"

    - name: docker login
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Build and Push Images
      run: |
        make docker-buildx -e TAG=${APPWRAPPER_VERSION} -e quay_repository=quay.io/ibm

    - name: Create Install YAML
      run: |
        make build-installer -e TAG=${APPWRAPPER_VERSION} -e quay_repository=quay.io/ibm

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ env.APPWRAPPER_VERSION }}
        fail_on_unmatched_files: true
        files: |
          ./dist/install.yaml
